# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["oss@fastly.com"]
description = "A TypeScript starter kit that uses Fastly's KV Store."
language = "javascript"
manifest_version = 2
name = "kv-store-typescript-starter-kit"
service_id = ""

[local_server]

  [local_server.backends]

  [local_server.kv_stores]

    [[local_server.kv_stores.my-store]]
      data = "placeholder"
      key = "placeholder"

    [[local_server.kv_stores.my-store]]
      key = "readme"
      path = "./README.md"

[scripts]
  build = "npm run build"
  post_init = "npm install"

[setup]

  [setup.kv_stores]

    [setup.kv_stores.my-store]
      description = "My first kv store"
