# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["oss@fastly.com"]
description = ""
language = "javascript"
manifest_version = 2
name = "object-store-typescript-example"
service_id = ""

[local_server]
[[local_server.object_store.my-store]]
  key  = "placeholder"
  data = "placeholder"

[[local_server.object_store.my-store]]
  key = "readme"
  path  = "./README.md"

[scripts]
  build = "npm run build"
